TPUART: UART.h File Reference
UART.h File Reference
This File contains the Macros and so to use the Interrupt driven USART Driver provided by Atmel. Many things taken from the esart_example_interrupt.c-File provided by Atmel.
#include "usart_driver.h"
#include "avr_compiler.h"
#include <string.h>
Macros
#define USART_TP USARTC0
#define USART_PC USARTC1
#define USART_DATA_TP USART_data_c0
#define USART_DATA_PC USART_data_c1
Functions
void usart_init_tpuart (void)
This Method enables and initializes the USART for the specific purpose to communicate with the TPUART1 Chip.
void usart_init_pc (void)
This Method enables and initializes the USART for the specific purpose to communicate with e.g. a PC.
void send_string_pgm_to_usart (USART_data_t *USART_data, const char *addr)
This Method uses the Program Space for e.g. Debug Strings and sends them to the given USART.
void send_string_to_usart (USART_data_t *USART_data, char *s)
This Method sends Strings to the given USART.
char receive_char_from_usart (USART_data_t *USART_data)
This Method waits till one char is in the given USART-Buffer - No Timeout, Blocks!!!!.
void receive_string_from_usart (USART_data_t *USART_data, char *string)
This Method reads out the data of the RingBuffer and returns a string.
void flush_USART_RXBuffer (USART_data_t *USART_data)
This Method flushs the RX Buffer.
Variables
USART_data_t USART_data_c0
USART_data_t USART_data_c1
Detailed Description
This File contains the Macros and so to use the Interrupt driven USART Driver provided by Atmel. Many things taken from the esart_example_interrupt.c-File provided by Atmel.
Author
Jan Baudis
Date
13.09.2016 16:17:27
Definition in file UART.h.
Macro Definition Documentation
USART_DATA_PC
#define USART_DATA_PC USART_data_c1
Definition at line 29 of file UART.h.
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), flush_USART_RXBuffer(), ISR(), main(), prod_request(), receive_char_from_usart(), receive_string_from_usart(), res_busymode(), reset_request(), setaddress(), shell_help(), state_request(), and usart_init_pc().
USART_DATA_TP
#define USART_DATA_TP USART_data_c0
Defines for easier handling of the USART PORTs.
Definition at line 28 of file UART.h.
Referenced by ackInfo(), act_busmon(), act_busymode(), ISR(), prod_request(), res_busymode(), reset_request(), setaddress(), state_request(), and usart_init_tpuart().
USART_PC
#define USART_PC USARTC1
Use the USART1 of Port C for the PC.
Definition at line 25 of file UART.h.
Referenced by usart_init_pc().
USART_TP
#define USART_TP USARTC0
For easier handling you may define here telling Names for the Macros and Data-structs.
Use the USART0 of Port C for the TPUART.
Definition at line 22 of file UART.h.
Referenced by usart_init_tpuart().
Function Documentation
flush_USART_RXBuffer()
void flush_USART_RXBuffer (USART_data_t * USART_data)
This Method flushs the RX Buffer.
Parameters
USART_data The USART_data_t struct instance.
Definition at line 198 of file UART.c.
References send_string_pgm_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
Referenced by act_busmon().
receive_char_from_usart()
char receive_char_from_usart (USART_data_t * USART_data)
This Method waits till one char is in the given USART-Buffer - No Timeout, Blocks!!!!.
Parameters
USART_data The USART_data_t struct instance.
Definition at line 175 of file UART.c.
References send_string_pgm_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
receive_string_from_usart()
void receive_string_from_usart (USART_data_t * USART_data, char * output)
This Method reads out the data of the RingBuffer and returns a string.
Parameters
USART_data The USART_data_t struct instance.
output The String-Pointer where the Output is stored
Definition at line 148 of file UART.c.
References send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
Referenced by ackInfo(), act_busmon(), enter_shell(), main(), prod_request(), reset_request(), setaddress(), and state_request().
send_string_pgm_to_usart()
void send_string_pgm_to_usart (USART_data_t * USART_data, const char * addr)
This Method uses the Program Space for e.g. Debug Strings and sends them to the given USART.
Parameters
USART_data The USART_data_t struct instance.
addr const char* to the pgmspace.
Definition at line 107 of file UART.c.
References USART_TXBuffer_PutByte().
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), flush_USART_RXBuffer(), main(), prod_request(), receive_char_from_usart(), receive_string_from_usart(), res_busymode(), reset_request(), setaddress(), shell_help(), and state_request().
send_string_to_usart()
void send_string_to_usart (USART_data_t * USART_data, char * s)
This Method sends Strings to the given USART.
Parameters
USART_data The USART_data_t struct instance.
s char* to transmit.
Definition at line 129 of file UART.c.
References USART_TXBuffer_PutByte().
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), main(), prod_request(), receive_string_from_usart(), res_busymode(), reset_request(), setaddress(), shell_help(), and state_request().
usart_init_pc()
void usart_init_pc (void)
This Method enables and initializes the USART for the specific purpose to communicate with e.g. a PC.
It Uses the USARTC1 and:
8 bit character size
No parity
1 stop bit
57600 Baud
Todo:
Maybe merge the init Functions. But think of a good way to configure the Params like Baudrate, Parity etc
Note
The Code is taken from the usart_example_interrupt.c-File and is edited to the needed values
Definition at line 69 of file UART.c.
References USART_Baudrate_Set, USART_DATA_PC, USART_Format_Set, USART_InterruptDriver_Initialize(), USART_PC, USART_Rx_Enable, USART_RxdInterruptLevel_Set, and USART_Tx_Enable.
Referenced by main().
usart_init_tpuart()
void usart_init_tpuart (void)
This Method enables and initializes the USART for the specific purpose to communicate with the TPUART1 Chip.
It Uses the USARTC0 and:
8 bit character size
Even parity
1 stop bit
19200 Baud
Todo:
Check if the TPUART2 Parity Specs from the DS also applies to the TPUART1 - TPUART1 Datasheet(p.10) is missing the parity specs - TPUART2 DS(p.21) says even, so lets try even; Maybe merge the Init functions
Note
The Code is taken from the usart_example_interrupt.c-File and is edited to the needed values
Definition at line 27 of file UART.c.
References USART_Baudrate_Set, USART_DATA_TP, USART_Format_Set, USART_InterruptDriver_Initialize(), USART_Rx_Enable, USART_RxdInterruptLevel_Set, USART_TP, and USART_Tx_Enable.
Referenced by main().
Variable Documentation
USART_data_c0
USART_data_t USART_data_c0
USART data struct used for USART 0 of Port C.
Definition at line 34 of file UART.h.
USART_data_c1
USART_data_t USART_data_c1
USART data struct used for USART 1 of Port C.
Definition at line 37 of file UART.h.
Referenced by ISR().