TPUART: UART.c File Reference
UART.c File Reference
This file contains the Basic Functions to use the interrupt driven USART Driver provided by Atmel and it sets the ISRs Many things taken from the usart_example_interrupt.c-File provided by Atmel.
#include "UART.h"
Functions
void usart_init_tpuart (void)
This Method enables and initializes the USART for the specific purpose to communicate with the TPUART1 Chip.
void usart_init_pc (void)
This Method enables and initializes the USART for the specific purpose to communicate with e.g. a PC.
void send_string_pgm_to_usart (USART_data_t *USART_data, const char *addr)
This Method uses the Program Space for e.g. Debug Strings and sends them to the given USART.
void send_string_to_usart (USART_data_t *USART_data, char *s)
This Method sends Strings to the given USART.
void receive_string_from_usart (USART_data_t *USART_data, char *output)
This Method reads out the data of the RingBuffer and returns a string.
char receive_char_from_usart (USART_data_t *USART_data)
This Method waits till one char is in the given USART-Buffer - No Timeout, Blocks!!!!.
void flush_USART_RXBuffer (USART_data_t *USART_data)
This Method flushs the RX Buffer.
ISR (USARTC0_RXC_vect)
Receive complete interrupt service routine.
ISR (USARTC0_DRE_vect)
Data register empty interrupt service routine.
ISR (USARTC1_RXC_vect)
Receive complete interrupt service routine.
ISR (USARTC1_DRE_vect)
Data register empty interrupt service routine.
Variables
volatile int ret_pressed = 0
Detailed Description
This file contains the Basic Functions to use the interrupt driven USART Driver provided by Atmel and it sets the ISRs Many things taken from the usart_example_interrupt.c-File provided by Atmel.
Author
Jan Baudis
Date
13.09.2016 16:17:44
Todo:
Change the UART-Functions - add an extra value for the Port used and not an simple string to select it in the Function for both Init Functions
Definition in file UART.c.
Function Documentation
flush_USART_RXBuffer()
void flush_USART_RXBuffer (USART_data_t * USART_data)
This Method flushs the RX Buffer.
Parameters
USART_data The USART_data_t struct instance.
Definition at line 201 of file UART.c.
References send_string_pgm_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
Referenced by act_busmon().
ISR() [1/4]
ISR (USARTC0_RXC_vect)
Receive complete interrupt service routine.
Receive complete interrupt service routine. Calls the common receive complete handler with pointer to the correct USART as argument.
Todo:
Think about if volatile for the USART_DATA_TP is needed!
Definition at line 228 of file UART.c.
References USART_DATA_TP, and USART_RXComplete().
ISR() [2/4]
ISR (USARTC0_DRE_vect)
Data register empty interrupt service routine.
Data register empty interrupt service routine. Calls the common data register empty complete handler with pointer to the correct USART as argument.
Todo:
Think about if volatile for the USART_DATA_TP is needed!
Definition at line 243 of file UART.c.
References USART_DATA_TP, and USART_DataRegEmpty().
ISR() [3/4]
ISR (USARTC1_RXC_vect)
Receive complete interrupt service routine.
Receive complete interrupt service routine. Calls the common receive complete handler with pointer to the correct USART as argument.
Todo:
Think about if volatile for the USART_DATA_PC is needed!
Note
Added a check to see if the Return-Key was pressed to trigger the "Shell"
If it receives the Return-Key(13) it changes ret_pressed so the Shell can evalute the command
Definition at line 258 of file UART.c.
References Usart_and_buffer::buffer, ret_pressed, USART_Buffer::RX, USART_Buffer::RX_Head, USART_data_c1, USART_DATA_PC, USART_RX_BUFFER_MASK, and USART_RXComplete().
ISR() [4/4]
ISR (USARTC1_DRE_vect)
Data register empty interrupt service routine.
Data register empty interrupt service routine. Calls the common data register empty complete handler with pointer to the correct USART as argument.
Todo:
Think about if volatile for the USART_DATA_PC is needed!
Definition at line 278 of file UART.c.
References USART_DATA_PC, and USART_DataRegEmpty().
receive_char_from_usart()
char receive_char_from_usart (USART_data_t * USART_data)
This Method waits till one char is in the given USART-Buffer - No Timeout, Blocks!!!!.
Parameters
USART_data The USART_data_t struct instance.
Definition at line 178 of file UART.c.
References send_string_pgm_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
receive_string_from_usart()
void receive_string_from_usart (USART_data_t * USART_data, char * output)
This Method reads out the data of the RingBuffer and returns a string.
Parameters
USART_data The USART_data_t struct instance.
output The String-Pointer where the Output is stored
Todo:
May add the ret val boolean to indicate if data was received at all
Definition at line 150 of file UART.c.
References send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_RXBuffer_GetByte(), and USART_RXBufferData_Available().
Referenced by ackInfo(), act_busmon(), enter_shell(), main(), prod_request(), reset_request(), send_data(), setaddress(), and state_request().
send_string_pgm_to_usart()
void send_string_pgm_to_usart (USART_data_t * USART_data, const char * addr)
This Method uses the Program Space for e.g. Debug Strings and sends them to the given USART.
Parameters
USART_data The USART_data_t struct instance.
addr const char* to the pgmspace.
Definition at line 107 of file UART.c.
References USART_TXBuffer_PutByte().
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), flush_USART_RXBuffer(), main(), prod_request(), receive_char_from_usart(), receive_string_from_usart(), res_busymode(), reset_request(), send_data(), setaddress(), shell_help(), and state_request().
send_string_to_usart()
void send_string_to_usart (USART_data_t * USART_data, char * s)
This Method sends Strings to the given USART.
Parameters
USART_data The USART_data_t struct instance.
s char* to transmit.
Definition at line 129 of file UART.c.
References USART_TXBuffer_PutByte().
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), main(), prod_request(), receive_string_from_usart(), res_busymode(), reset_request(), send_data(), setaddress(), shell_help(), and state_request().
usart_init_pc()
void usart_init_pc (void)
This Method enables and initializes the USART for the specific purpose to communicate with e.g. a PC.
It Uses the USARTC1 and:
8 bit character size
No parity
1 stop bit
57600 Baud
Todo:
Maybe merge the init Functions. But think of a good way to configure the Params like Baudrate, Parity etc
Note
The Code is taken from the usart_example_interrupt.c-File and is edited to the needed values
Definition at line 69 of file UART.c.
References USART_Baudrate_Set, USART_DATA_PC, USART_Format_Set, USART_InterruptDriver_Initialize(), USART_PC, USART_Rx_Enable, USART_RxdInterruptLevel_Set, and USART_Tx_Enable.
Referenced by main().
usart_init_tpuart()
void usart_init_tpuart (void)
This Method enables and initializes the USART for the specific purpose to communicate with the TPUART1 Chip.
It Uses the USARTC0 and:
8 bit character size
Even parity
1 stop bit
19200 Baud
Todo:
Check if the TPUART2 Parity Specs from the DS also applies to the TPUART1 - TPUART1 Datasheet(p.10) is missing the parity specs - TPUART2 DS(p.21) says even, so lets try even; Maybe merge the Init functions
Note
The Code is taken from the usart_example_interrupt.c-File and is edited to the needed values
Definition at line 27 of file UART.c.
References USART_Baudrate_Set, USART_DATA_TP, USART_Format_Set, USART_InterruptDriver_Initialize(), USART_Rx_Enable, USART_RxdInterruptLevel_Set, USART_TP, and USART_Tx_Enable.
Referenced by main().
Variable Documentation
ret_pressed
volatile int ret_pressed = 0
Definition at line 11 of file UART.c.
Referenced by ackInfo(), enter_shell(), ISR(), main(), send_data(), and setaddress().