TPUART: clock.c File Reference
clock.c File Reference
This file contains the Function to init, calibrate and change the clock.
Macros
#define F_CPU 32000000UL
Functions
void set_clock_32MHz (void)
This function inits, calibrates and changes the clock.
Detailed Description
This file contains the Function to init, calibrate and change the clock.
Author
Jan Baudis
Date
11.09.2016 14:24:30
Definition in file clock.c.
Macro Definition Documentation
F_CPU
#define F_CPU 32000000UL
Function Documentation
set_clock_32MHz()
void set_clock_32MHz (void)
This function inits, calibrates and changes the clock.
It enables the 32kHz ref Clock for the Autocalibration and also executes the calibration. Afterwards it enables and changes to the 32MHz internal Clock and also disables the 2MHz clock. Eventually it Locks the current Clock config.
Note
The 32kHz Clock remains active.
Todo:
Since I am not sure if the 32kHz Clock is enabled by default i wont disable it afterwards - so look it up and maybe change it.
Definition at line 18 of file clock.c.
References CLKSYS_AutoCalibration_Enable(), CLKSYS_Configuration_Lock(), CLKSYS_Disable(), CLKSYS_Enable, CLKSYS_IsReady, and CLKSYS_Main_ClockSource_Select().
Referenced by main().