TPUART: clock.h File Reference
clock.h File Reference
This file is the Headerfile for the clock-File. It contains the prototypes of the functions and the usual macros.
#include "clksys_driver.h"
Functions
void set_clock_32MHz (void)
This function inits, calibrates and changes the clock.
Detailed Description
This file is the Headerfile for the clock-File. It contains the prototypes of the functions and the usual macros.
Author
Jan Baudis
Date
11.09.2016 14:24:45
Definition in file clock.h.
Function Documentation
set_clock_32MHz()
void set_clock_32MHz (void)
This function inits, calibrates and changes the clock.
It enables the 32kHz ref Clock for the Autocalibration and also executes the calibration. Afterwards it enables and changes to the 32MHz internal Clock and also disables the 2MHz & 32kHz clocks. Eventually it Locks the current Clock config.
Definition at line 16 of file clock.c.
References CLKSYS_AutoCalibration_Enable(), CLKSYS_Configuration_Lock(), CLKSYS_Disable(), CLKSYS_Enable, CLKSYS_IsReady, and CLKSYS_Main_ClockSource_Select().
Referenced by main().