TPUART: main.c File Reference
main.c File Reference
This file is the main-File. It calls all the fancy Functions and so on.
#include "main.h"
#include "UART.h"
Functions
uint8_t USART_test (USART_data_t *usart_data)
int main (void)
This is the main-Function.
Variables
int volatile ret_pressed
Detailed Description
This file is the main-File. It calls all the fancy Functions and so on.
Author
Jan Baudis
Date
08.09.2016 01:50:07
Definition in file main.c.
Function Documentation
main()
int main (void)
This is the main-Function.
It calls all the fancy Functions. It does things.
Enter the "Shell"!
Definition at line 29 of file main.c.
References enter_shell(), receive_string_from_usart(), ret_pressed, send_string_pgm_to_usart(), send_string_to_usart(), set_clock_32MHz(), USART_DATA_PC, usart_init_pc(), and usart_init_tpuart().
USART_test()
uint8_t USART_test (USART_data_t * usart_data)
Definition at line 12 of file main.c.
References Usart_and_buffer::buffer, USART_Buffer::RX, and USART_Buffer::RX_Tail.
Variable Documentation
ret_pressed
int volatile ret_pressed
Definition at line 11 of file UART.c.
Referenced by main().