TPUART: shell.c File Reference
shell.c File Reference
Implements a basic "shell" to communicate with the TPUART/KNX and Debug things. Data sheet KNX EIB TP-UART 2+ page 22 and following.
#include "shell.h"
Functions
void enter_shell (USART_data_t *USART_data)
Enter the "Shell".
void reset_request (void)
Shell-Function for the U_reset.request-Service.
void state_request (void)
Shell-Function for the U_state.request-Service.
void act_busmon (void)
Shell-Function for the U_ActivateBusmon-Service.
void prod_request (void)
Shell-Function for the U_ProductID.request-Service.
void act_busymode (void)
Shell-Function for the U_ActivateBusyMode.
void res_busymode (void)
Shell-Function for the U_ResetBusyMode.
void setaddress (void)
Shell-Function for the U_SetAddress.
void ackInfo (void)
Shell-Function for the U_AckInformation-Service.
void shell_help (void)
Variables
int volatile ret_pressed
char command [33]
Detailed Description
Implements a basic "shell" to communicate with the TPUART/KNX and Debug things. Data sheet KNX EIB TP-UART 2+ page 22 and following.
Author
Jan Baudis
Date
03.12.2016 01:01:54
Note
Buffer Size in the usart_driver.h has to be changed if the commands are too big - it only evaluates the received string when enter is pressed.
Todo:
Maybe disable RX for the PC while working on a command!
Definition in file shell.c.
Function Documentation
ackInfo()
void ackInfo (void)
Shell-Function for the U_AckInformation-Service.
Sends the U_AckInformation to the TPUART. This must be sent latest 2,8ms after receiving the address type octet of an addressed frame. Its used to evaluate the Address on the Host side. More on p. 25 ff off the TPUART 2+ Data sheet.
Todo:
Implement this as a feature for receiving Frames in general. Since it only makes sense if its send after 2,8ms of an addressed frame. Look up if it can set more than one Flag! - Maybe its also important to implement for the Bus-Sniffer
Definition at line 454 of file shell.c.
References command, receive_string_from_usart(), ret_pressed, send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
act_busmon()
void act_busmon (void)
Shell-Function for the U_ActivateBusmon-Service.
Sends the U_ActivateBusmon to the TPUART and prints the Output as bits to the PC. Listens till it receives any Key from the PC. Then it Resets the Chip since its the Only way to quit the Busmon-Mode of the TPUART.
Todo:
Implement an end of Packet detection to print out some useful Information for the Bits.
Definition at line 175 of file shell.c.
References command, flush_USART_RXBuffer(), receive_string_from_usart(), reset_request(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, USART_RXBufferData_Available(), and USART_TXBuffer_PutByte().
Referenced by enter_shell().
act_busymode()
void act_busymode (void)
Shell-Function for the U_ActivateBusyMode.
Sends the U_ActivateBusyMode to the TPUART. TP-UART responses on every Packet which is addressed to him with BUSY within 700ms (+-10ms). All Packets are send to the Host and if the Host confirms one with U_Ackinfo it will leave BusyMode as well when reseted.
Todo:
May add something; Dunno like a Listen Mode for 700ms;
Definition at line 268 of file shell.c.
References command, send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
enter_shell()
void enter_shell (USART_data_t * USART_data)
Enter the "Shell".
In the "Shell" we can e.g. use the Services of the TPUART
Parameters
USART_data The USART_data_t struct instance.
Definition at line 22 of file shell.c.
References ackInfo(), act_busmon(), act_busymode(), command, prod_request(), receive_string_from_usart(), res_busymode(), reset_request(), ret_pressed, send_string_pgm_to_usart(), send_string_to_usart(), setaddress(), shell_help(), state_request(), and USART_DATA_PC.
Referenced by main().
prod_request()
void prod_request (void)
Shell-Function for the U_ProductID.request-Service.
Sends the U_ProductID.request to the TPUART and prints the Output as bits to the PC
Definition at line 224 of file shell.c.
References command, receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
res_busymode()
void res_busymode (void)
Shell-Function for the U_ResetBusyMode.
Sends the U_ResetBusyMode to the TPUART. So the TPUART immediately leaves the BUSY Mode.
Definition at line 292 of file shell.c.
References command, send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
reset_request()
void reset_request (void)
Shell-Function for the U_reset.request-Service.
Sends the U_reset.request to the TPUART and prints the Output as bits to the PC
Definition at line 89 of file shell.c.
References command, receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by act_busmon(), and enter_shell().
setaddress()
void setaddress (void)
Shell-Function for the U_SetAddress.
Sends the U_SetAddress to the TPUART and prompts for the Address to set.
| physical address high | | physical address low |
| 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 | | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
| a | a | a | a | l | l | l | l | | d | d | d | d | d | d | d | d |
Definition at line 322 of file shell.c.
References command, receive_string_from_usart(), ret_pressed, send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
shell_help()
void shell_help (void)
Definition at line 507 of file shell.c.
References command, send_string_pgm_to_usart(), send_string_to_usart(), and USART_DATA_PC.
Referenced by enter_shell().
state_request()
void state_request (void)
Shell-Function for the U_state.request-Service.
Sends the U_state.request to the TPUART and prints the Output as bits to the PC
Definition at line 131 of file shell.c.
References command, receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
Variable Documentation
command
char command[33]
Definition at line 13 of file shell.c.
Referenced by ackInfo(), act_busmon(), act_busymode(), enter_shell(), prod_request(), res_busymode(), reset_request(), setaddress(), shell_help(), and state_request().
ret_pressed
int volatile ret_pressed
Definition at line 11 of file UART.c.
Referenced by ackInfo(), enter_shell(), ISR(), and setaddress().