TPUART: shell.h File Reference
shell.h File Reference
Corresponding header-File.
#include "usart_driver.h"
#include "avr_compiler.h"
#include "UART.h"
#include <string.h>
Functions
void enter_shell (USART_data_t *USART_data)
Enter the "Shell".
void shell_help (void)
void reset_request (void)
Shell-Function for the U_reset.request-Service.
void state_request (void)
Shell-Function for the U_state.request-Service.
void act_busmon (void)
Shell-Function for the U_ActivateBusmon-Service.
Detailed Description
Corresponding header-File.
Author
Jan Baudis
Date
03.12.2016 01:03:19
Definition in file shell.h.
Function Documentation
act_busmon()
void act_busmon (void)
Shell-Function for the U_ActivateBusmon-Service.
Sends the U_ActivateBusmon to the TPUART and prints the Output as bits to the PC. Listens till it receives any Key from the PC. Then it Resets the Chip since its the Only way to quit the Busmon-Mode of the TPUART.
Todo:
Implement an end of Packet detection to print out some useful Information for the Bits.
Definition at line 175 of file shell.c.
References command, flush_USART_RXBuffer(), receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, USART_RXBufferData_Available(), and USART_TXBuffer_PutByte().
Referenced by enter_shell().
enter_shell()
void enter_shell (USART_data_t * USART_data)
Enter the "Shell".
In the "Shell" we can e.g. use the Services of the TPUART
Parameters
usart_data The USART_data_t struct instance.
Definition at line 22 of file shell.c.
References act_busmon(), command, receive_string_from_usart(), reset_request(), ret_pressed, send_string_pgm_to_usart(), send_string_to_usart(), shell_help(), state_request(), and USART_DATA_PC.
Referenced by main().
reset_request()
void reset_request (void)
Shell-Function for the U_reset.request-Service.
Sends the U_reset.request to the TPUART and prints the Output as bits to the PC
Definition at line 89 of file shell.c.
References command, receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by enter_shell().
shell_help()
void shell_help (void)
Definition at line 219 of file shell.c.
References command, send_string_pgm_to_usart(), send_string_to_usart(), and USART_DATA_PC.
Referenced by enter_shell().
state_request()
void state_request (void)
Shell-Function for the U_state.request-Service.
Sends the U_state.request to the TPUART and prints the Output as bits to the PC
Definition at line 131 of file shell.c.
References command, receive_string_from_usart(), send_string_pgm_to_usart(), send_string_to_usart(), USART_DATA_PC, USART_DATA_TP, USART_RX_BUFFER_SIZE, and USART_TXBuffer_PutByte().
Referenced by enter_shell().